import { dbConnection, closeConnection } from "./config/mongoConnection.js";
import { users, products, posts } from "./config/mongoCollections.js";
import { ObjectId } from "mongodb";

const userList = [
  {
    _id: "mRdeR8wDRzLVEbeer5PpbJY6TDE3",
    email: "lfu7@stevens.edu",
    firstname: "Luoyi",
    lastname: "Fu",
    favorite: [],
    comments: [],
  },
  {
    _id: "8C5bGSz1FRVbAQ47EDnDSvmKsqg2",
    email: "cwu34@stevens.edu",
    firstname: "Jason",
    lastname: "Wu",
    favorite: [],
    comments: [],
  },
  {
    _id: "7SKDog0fjKOeS1jeuq32a9vYPue2",
    email: "dchen30@stevens.edu",
    firstname: "Karol",
    lastname: "Chen",
    favorite: [
      // "657e177ed64d25302ad3b2c5",
      // "657e177ed64d25302ad3b2c6",
      // "657e177ed64d25302ad3b2c7",
      // "657e177ed64d25302ad3b2c8",
      // "657e177ed64d25302ad3b2c9",
    ],
    comments: [],
  },
];
const productList = [
  {
    _id: new ObjectId(),
    name: "pencils",
    price: 3,
    date: new Date("2023-12-01"),
    description: "5 pencils",
    condition: "Functional",
    seller_id: "mRdeR8wDRzLVEbeer5PpbJY6TDE3",
    buyer_id: null,
    image: "7ENPNeTB3qkgvrS+W9aXTg==",
    category: "Other",
    status: "active",
    possible_buyers: [],
    completion_date: null,
  },
  {
    _id: new ObjectId(),
    name: "phone",
    price: 500,
    date: new Date("2023-12-01"),
    description: "test",
    condition: "Gently Used",
    seller_id: "7SKDog0fjKOeS1jeuq32a9vYPue2",
    buyer_id: null,
    image:
      "https://vviv-images.s3.us-west-1.amazonaws.com/phone1702950060654deeppurple1.webp",
    category: "Electronics",
    status: "active",
    possible_buyers: [],
    completion_date: null,
  },
  {
    // _id: {
    //   $oid: "6580f7bb26a29e6992110a1f",
    // },
    _id: new ObjectId(),
    name: "desk",
    price: 12,
    date: new Date("2023-12-01"),
    description: "test",
    condition: "Brand New",
    seller_id: "7SKDog0fjKOeS1jeuq32a9vYPue2",
    buyer_id: null,
    image:
      "https://vviv-images.s3.us-west-1.amazonaws.com/desk1702950840957download.png",
    category: "Furniture",
    status: "active",
    possible_buyers: [],
    completion_date: null,
  },
  {
    _id: new ObjectId(),
    name: "python 101",
    price: 10,
    date: new Date("2023-12-11"),
    description: "python book",
    condition: "Brand New",
    seller_id: "8C5bGSz1FRVbAQ47EDnDSvmKsqg2",
    buyer_id: null,
    image: "7ENPNeTB3qkgvrS+W9aXTg==",
    category: "Book",
    status: "active",
    possible_buyers: [],
    completion_date: null,
  },
  {
    _id: new ObjectId(),
    name: "java 101",
    price: 10,
    date: new Date("2023-12-12"),
    description: "java book",
    condition: "Brand New",
    seller_id: "mRdeR8wDRzLVEbeer5PpbJY6TDE3",
    buyer_id: null,
    image: "7ENPNeTB3qkgvrS+W9aXTg==",
    category: "Book",
    status: "active",
    possible_buyers: [],
    completion_date: null,
  },
  {
    _id: new ObjectId(),
    name: "javascript 101",
    price: 10,
    date: new Date("2023-12-13"),
    description: "javascript book",
    condition: "Brand New",
    seller_id: "8C5bGSz1FRVbAQ47EDnDSvmKsqg2",
    buyer_id: null,
    image: "7ENPNeTB3qkgvrS+W9aXTg==",
    category: "Book",
    status: "active",
    possible_buyers: [],
    completion_date: null,
  },
  {
    _id: new ObjectId(),
    name: "C# 101",
    price: 10,
    date: new Date("2023-12-14"),
    description: "C# book",
    condition: "Brand New",
    seller_id: "mRdeR8wDRzLVEbeer5PpbJY6TDE3",
    buyer_id: null,
    image: "7ENPNeTB3qkgvrS+W9aXTg==",
    category: "Book",
    status: "active",
    possible_buyers: [],
    completion_date: null,
  },
  {
    _id: new ObjectId(),
    name: "C++ 101",
    price: 10,
    date: new Date("2023-12-15"),
    description: "C++ book",
    condition: "Brand New",
    seller_id: "mRdeR8wDRzLVEbeer5PpbJY6TDE3",
    buyer_id: null,
    image: "7ENPNeTB3qkgvrS+W9aXTg==",
    category: "Book",
    status: "active",
    possible_buyers: [],
    completion_date: null,
  },
  {
    _id: new ObjectId(),
    name: "Kotlin 101",
    price: 10,
    date: new Date("2023-12-16"),
    description: "Kotlin book",
    condition: "Brand New",
    seller_id: "mRdeR8wDRzLVEbeer5PpbJY6TDE3",
    buyer_id: null,
    image: "7ENPNeTB3qkgvrS+W9aXTg==",
    category: "Book",
    status: "active",
    possible_buyers: [],
    completion_date: null,
  },
  {
    _id: new ObjectId(),
    name: "css",
    price: 1,
    date: new Date(),
    description: "css",
    condition: "Brand New",
    seller_id: "mRdeR8wDRzLVEbeer5PpbJY6TDE3",
    buyer_id: null,
    image:
      "https://vviv-images.s3.us-west-1.amazonaws.com/css1702976481029home.jpeg",
    category: "Book",
    status: "active",
    possible_buyers: [],
    completion_date: null,
  },
];
const postList = [
  {
    _id: new ObjectId(),
    buyer_id: "mRdeR8wDRzLVEbeer5PpbJY6TDE3",
    seller_id: null,
    item: "Book",
    category: "Book",
    price: 10,
    condition: "Brand New",
    date: new Date(),
    description: "textbook",
    status: "active",
    possible_sellers: [],
    completion_date: null,
  },
  {
    _id: new ObjectId(),
    buyer_id: "7SKDog0fjKOeS1jeuq32a9vYPue2",
    seller_id: null,
    item: "chair",
    category: "Furniture",
    price: 10,
    condition: "Like New",
    date: new Date(),
    description: "",
    status: "active",
    possible_sellers: [],
    completion_date: null,
  },
  {
    _id: new ObjectId(),
    buyer_id: "mRdeR8wDRzLVEbeer5PpbJY6TDE3",
    seller_id: null,
    item: "Pen",
    category: "Book",
    price: 10,
    condition: "Brand New",
    date: new Date(),
    description: "black pen",
    status: "inactive",
    possible_sellers: [],
    completion_date: null,
  },
  {
    _id: new ObjectId(),
    buyer_id: "mRdeR8wDRzLVEbeer5PpbJY6TDE3",
    seller_id: "8C5bGSz1FRVbAQ47EDnDSvmKsqg2",
    item: "Book",
    category: "Book",
    price: 10,
    condition: "Brand New",
    date: new Date("2023-12-07"),
    description: "textbook",
    status: "completed",
    possible_sellers: ["8C5bGSz1FRVbAQ47EDnDSvmKsqg2"],
    completion_date: new Date("2023-12-08"),
  },
  {
    _id: new ObjectId(),
    buyer_id: "8C5bGSz1FRVbAQ47EDnDSvmKsqg2",
    seller_id: "mRdeR8wDRzLVEbeer5PpbJY6TDE3",
    item: "Phone",
    category: "Electronics",
    price: 10,
    condition: "Brand New",
    date: new Date("2023-12-01"),
    description: "",
    status: "completed",
    possible_sellers: ["mRdeR8wDRzLVEbeer5PpbJY6TDE3"],
    completion_date: new Date("2023-12-08"),
  },
];

const main = async () => {
  const db = await dbConnection();
  await db.dropDatabase();
  const userCollection = await users();
  const productCollection = await products();
  const postCollection = await posts();

  await userCollection.insertMany(userList);
  await productCollection.insertMany(productList);
  await postCollection.insertMany(postList);

  console.log("Done seeding database");
  await closeConnection();
};

main().catch(console.log);
